### ISSUE TITLE
can not load keras model!

### ISSUE THREAD

**Issue by mayidu** [irwanafandi24/Disease-Identification#1]
hello, I use you code, but there are some problems!
model = tf.keras.models.load_model((model_path), custom_objects={'KerasLayer': hub.KerasLayer})
always errors!

**Comment by irwanafandi24** [comment]
Hai May
Have you downloaded the model?
First, you need to download the classification model in this download
<https://drive.google.com/file/d/1m-SPJFvq9GnmJoaF4BKREq1mUe9RNQOg/view>
link.
Second, copast the download file to the model folder.
Then try running the python file (flask), it should run.
Btw, thank you to contacting me

**Comment by mayidu** [comment]
Yes! I had downloaded the model and put in the model folder. 
I only run the keras load mode, there are problem, 
eg：
Traceback (most recent call last):
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 1440, in connect
    super().connect()
  File "/hom/envs/tf_env/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/hom/envs/tf_env/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/hom/envs/tf_env/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mainmy.py", line 41, in <module>
    model = tf.keras.models.load_model((h5_save_path), custom_objects={'KerasLayer': hub.KerasLayer})
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/saving/save.py", line 201, in load_model
    compile)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/saving/hdf5_format.py", line 181, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/saving/model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/layers/serialization.py", line 212, in deserialize
    printable_module_name='layer')
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 678, in deserialize_keras_object
    list(custom_objects.items())))
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/engine/sequential.py", line 433, in from_config
    custom_objects=custom_objects)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/layers/serialization.py", line 212, in deserialize
    printable_module_name='layer')
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 681, in deserialize_keras_object
    deserialized_obj = cls.from_config(cls_config)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/keras/engine/base_layer.py", line 748, in from_config
    return cls(**config)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 153, in __init__
    self._func = load_module(handle, tags, self._load_options)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 449, in load_module
    return module_v2.load(handle, tags=tags, options=set_load_options)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 92, in load
    module_path = resolve(handle)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 47, in resolve
    return registry.resolver(handle)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/registry.py", line 51, in __call__
    return impl(*args, **kwargs)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 68, in __call__
    self._lock_file_timeout_sec())
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 418, in atomic_download
    download_fn(handle, tmp_dir)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 63, in download
    response = self._call_urlopen(request)
  File "/hom/envs/tf_env/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 522, in _call_urlopen
    return urllib.request.urlopen(request)
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/hom/envs/tf_env/lib/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

Is it my environment error？
I use thensorflow==2.6.1， tensorhub==0.12.0
cudn 11.3.1
cudnn 8.2.1
Is it caused by a mismatch between tensorflow and tensorhub?
